/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/tools/convert': RouteRecordInfo<'/tools/convert', '/tools/convert', Record<never, never>, Record<never, never>>,
    '/tools/pointselect': RouteRecordInfo<'/tools/pointselect', '/tools/pointselect', Record<never, never>, Record<never, never>>,
    '/trip/bracke/(TripBracke)': RouteRecordInfo<'/trip/bracke/(TripBracke)', '/trip/bracke', Record<never, never>, Record<never, never>>,
    '/trip/flinders/(TripFlinders)': RouteRecordInfo<'/trip/flinders/(TripFlinders)', '/trip/flinders', Record<never, never>, Record<never, never>>,
    '/trip/gavle/(TripGavle)': RouteRecordInfo<'/trip/gavle/(TripGavle)', '/trip/gavle', Record<never, never>, Record<never, never>>,
    '/trip/ljusdal/(TripLjusdal)': RouteRecordInfo<'/trip/ljusdal/(TripLjusdal)', '/trip/ljusdal', Record<never, never>, Record<never, never>>,
    '/trip/personalComponents/AboutDetail': RouteRecordInfo<'/trip/personalComponents/AboutDetail', '/trip/personalComponents/AboutDetail', Record<never, never>, Record<never, never>>,
    '/trip/sweden/(TripSweden)': RouteRecordInfo<'/trip/sweden/(TripSweden)', '/trip/sweden', Record<never, never>, Record<never, never>>,
    '/trip/test/(TripTest)': RouteRecordInfo<'/trip/test/(TripTest)', '/trip/test', Record<never, never>, Record<never, never>>,
  }
}
